# GET http://localhost:3030/translate/portugueseToUmbundu?palavra=abacate


# GET http://localhost:3030/translate/portugueseToChokwe?palavra=Conhecimento


# POST http://localhost:3030/translate/portugueseToUmbundu?portugues=abacate&umbundu=epako


# POST http://localhost:3030/translate/inserirTodo
